name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adoptopenjdk'
          java-version: '17'
          cache: 'maven'

      - name: Maven Build
        run: |
          echo "Running maven clean now"
          mvn clean
          echo "Packaging artifacts"
          mvn package
          echo "Maven artifact created"
          ls -la

      - name: SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Pushing artifact to SonarQube for code analysis"
          mvn sonar:sonar -Dsonar.qualitygate.wait=true

      - name: Nexus Artifacts Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          echo "Pushing to Nexus repositories"
          mvn deploy -s ./settings.xml

      - name: Deploy to Tomcat
        env:
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          echo "Deploying to Tomcat"
          rm -rf '/tmp/demojenkins'
          mvn tomcat7:deploy -Dtomcat.username=${{ secrets.TOMCAT_USERNAME }} -Dtomcat.password=${{ secrets.TOMCAT_PASSWORD }} -Dtomcat.url=http://tomcat:8080
